language: node_js
node_js:
  - "9.4.0"


script:
  - npm install
  #- npm install core-js -g
  - npm test
  - cd webapp/nodeapp-express/
  - npm install
  - ls -lrt
  - pwd
  - cd ../..
  - cd ..
  - ls -lrt

after_success:
  - pwd
  - ls -ltr
  - mkdir codedeploy_artifact
  - cp csye6225-fall2018/infrastructure/aws/codedeploy/*.sh ./codedeploy_artifact/
  - cp csye6225-fall2018/infrastructure/aws/codedeploy/*.yml ./codedeploy_artifact/
  - cd csye6225-fall2018/
  - zip -r csye6225-fall2018.zip ./* >/dev/null
  - cp csye6225-fall2018.zip ./../codedeploy_artifact/
  - rm -rf csye6225-fall2018.zip
  - pwd
  - cd ..
  - cd codedeploy_artifact/
  - zip -r csye6225-fall2018-$TRAVIS_JOB_NUMBER.zip *.yml *.sh csye6225-fall2018.zip >/dev/null 2>&1
  - rm -rf csye6225-fall2018.zip *.yml *.sh
  - pwd
  - ls -lrt
  - cd ..


deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      branch: Assignment-5

#   - provider: codedeploy
#     access_key_id: $access_key_id
#     bucket: $s3_bucket
#     key: csye6225-fall2018-$TRAVIS_JOB_NUMBER.zip
#     bundle_type: zip
#     application: $application
#     deployment_group: $deployment_group
#     region: us-east-1
#     secret_access_key: $secret_access_key
#     wait-until-deployed: true
#     on:
#       branch: Assignment-5


# cache:
#   directories:
#     -node_modules

# notifications:
#   email:
#     on_success: always
#     on_failure: always